ALTER TABLE USERS
ADD FOREIGN KEY (fileId) References FILES(fileId);

ALTER TABLE USERS
ADD FOREIGN KEY (timeDate) REFERENCES SELECTS (timeDate);

ALTER TABLE FILES
ADD FOREIGN KEY (timeDate) REFERENCES SELECTS (timeDate);

ALTER TABLE FILES
    FOREIGN KEY (songID) REFERENCES SONG (songID);

ALTER TABLE SONG
ADD FOREIGN KEY (fileId) REFERENCES FILES(fileId);

ALTER TABLE SELECTS
ADD FOREIGN KEY (phoneNum) REFERENCES USERS (phoneNum);

ALTER TABLE SELECTS
 ADD   FOREIGN KEY (fileId) REFERENCES FILES (fileId);

ALTER TABLE TYPECONTRIBUTOR
ADD FOREIGN KEY (songId) REFERENCES SONG (songId);

ALTER TABLE TYPECONTRIBUTOR
ADD FOREIGN KEY (contributorId) REFERENCES CONTRIBUTOR(contributorId);
